services:
  modelapi:
    build:
      context: ./modelapi
      dockerfile: Dockerfile
    container_name: modelapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./modelapi:/modelapi
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --workers=1
    environment:
      - ENABLE_METRICS=true

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--web.listen-address=0.0.0.0:9090'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
