# prometheus.yml

global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: fastapi
  honor_labels: true
  static_configs:
  - targets:
    - fastapi-app:8000  # metrics from model

- job_name: node
  static_configs:
  - targets:
    - localhost:9100  # 또는 node_exporter가 띄워진 서버 IP:포트